TRAINING_LOGS = [
    ("Payment gateway timeout while processing transaction", "PAYMENT_ERROR"),
    ("Card authorization failed for order checkout", "PAYMENT_ERROR"),
    ("UPI payment declined by bank switch", "PAYMENT_ERROR"),
    ("Payment service returned insufficient funds error", "PAYMENT_ERROR"),
    ("Refund request failed due to gateway unavailable", "PAYMENT_ERROR"),
    ("Transaction settlement mismatch detected", "PAYMENT_ERROR"),
    ("Payment callback signature verification failed", "PAYMENT_ERROR"),
    ("Wallet debit failed after checkout confirmation", "PAYMENT_ERROR"),
    ("Login failed because password is invalid", "LOGIN_ERROR"),
    ("User authentication token expired", "LOGIN_ERROR"),
    ("Multiple failed login attempts detected", "LOGIN_ERROR"),
    ("Account locked after invalid credentials", "LOGIN_ERROR"),
    ("OAuth callback failed during user sign in", "LOGIN_ERROR"),
    ("Session expired while validating refresh token", "LOGIN_ERROR"),
    ("Unauthorized login attempt from blocked ip", "LOGIN_ERROR"),
    ("Two factor authentication code mismatch", "LOGIN_ERROR"),
    ("Database connection timeout", "DATABASE_ERROR"),
    ("MySQL deadlock found when trying to get lock", "DATABASE_ERROR"),
    ("SQL query failed due to duplicate key", "DATABASE_ERROR"),
    ("Database pool exhausted for service", "DATABASE_ERROR"),
    ("Unable to commit transaction to database", "DATABASE_ERROR"),
    ("Replica lag exceeded safe threshold", "DATABASE_ERROR"),
    ("Schema migration failed on users table", "DATABASE_ERROR"),
    ("Database connection refused by host", "DATABASE_ERROR"),
    ("API request timeout from downstream service", "API_ERROR"),
    ("External API returned 500 internal server error", "API_ERROR"),
    ("REST endpoint unavailable for customer profile", "API_ERROR"),
    ("Rate limit exceeded on partner API", "API_ERROR"),
    ("Bad gateway from notification API", "API_ERROR"),
    ("API response payload validation failed", "API_ERROR"),
    ("Webhook delivery failed with HTTP 503", "API_ERROR"),
    ("Service dependency returned malformed JSON", "API_ERROR"),
    ("Unauthorized banking access detected", "SECURITY_THREAT"),
    ("Suspicious login from blocked ip address", "SECURITY_THREAT"),
    ("Brute force attack detected on customer account", "SECURITY_THREAT"),
    ("Authentication token replay attack blocked", "SECURITY_THREAT"),
    ("Security breach attempt against admin endpoint", "SECURITY_THREAT"),
    ("Malware signature detected in uploaded payload", "SECURITY_THREAT"),
]
